baseURL = "http://localhost"
title = "KDK Docs"
theme = "hugo-geekdoc"
contentDir = "../doc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[params]
  # Enable TOC globally
  geekdocToC = true

  # Set ToC level
  geekdocToCLevel = 3

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"

[taxonomies]
   tag = "tags"
