---
name: khulnasoft_base.CIConfigFile
description: |
  Checks that the `.khulnasoft-ci.yml` file is referenced properly.
extends: existence
message: "Change the file name to be exactly '.khulnasoft-ci.yml'."
link: https://docs.khulnasoft.com/development/documentation/styleguide/availability_details/
vocab: false
level: error
scope: raw
raw:
  - '(?!`\.khulnasoft-ci\.yml`)`.?khulnasoft.?ci.?ya?ml`'
